language: csharp
solution: ./Project/Algorithm.sln
dotnet: 3.1

install:
  - nuget restore ./Project/Algorithm.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  # - sudo apt-get install nunit-console
  
script:
  # - dotnet build ./Project/Algorithm.sln
  # - dotnet test ./Project/Algorithm.sln
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Project/Tests/bin/Release/.netcoreapp,version=v3.1/Tests.dll