language: csharp
solution: ./Project/Algorithm.sln
dotnet: 3.1.0

install:
  - sudo apt-get install nunit-console
  - nuget restore ./Project/Algorithm.sln
  
script:
  - dotnet build ./Project/Algorithm.sln
  - dotnet test ./Project/Algorithm.sln
