language: csharp
solution: ./AlgorithmSln/AlgorithmSln.sln
dotnet: 3.1

install:
  - sudo apt-get install nunit-console
  - nuget restore ./AlgorithmSln/AlgorithmSln.sln
  
script:
  - dotnet test ./AlgorithmSln/AlgorithmSln.sln
