language: csharp
solution: ./Project/Algorithm.sln

install:
  - nuget restore ./Project/Algorithm.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  # - sudo apt-get install nunit-console
  
script:
  # - dotnet build ./Project/Algorithm.sln
  # - dotnet test ./Project/Algorithm.sln
  - msbuild /p:Configuration=Release ./Project/Algorithm.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll